---
########Selinux Firewalld Disable########
- name: Selinux dsiable
  lineinfile:
    dest: /etc/selinux/config
    regexp: '^SELINUX='
    line: 'SELINUX=disabled'
- name: Selinux stop
  selinux: state=disabled
- name: Firewalld disable
  service: name=firewalld state=stopped enabled=no

######## nginx install ##################
- name: Install nginx
  yum:
    name: 
      - nginx
      - epel-release
    state: latest
- name: COPY Nginx Configuration File
  template: 
    src: k8s.conf 
    dest: /etc/nginx/nginx.conf
  notify: restart nginx 
