---
- name: 更新YUM源
  shell: wget -O /etc/yum.repos.d/docker-ce.repo https://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo warn=False

- name: 安装docker-CE
  yum: 
    name: docker-ce 
    state: present

- name: docker启动
  service: 
    name: docker.service 
    enabled: yes 
    state: started

- name: 加载docker配置文件
  template:
    src: "daemon.json"
    dest: "{{ docker_config_path }}/daemon.json"
  notify: restart docker
