---
- block:
  - shell: wget -O /etc/yum.repos.d/docker-ce.repo https://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo warn=False
  - yum: name={{ item }} state=present
    loop:
      - docker-ce
  - service: name=docker.service enabled=yes state=started

  - name: COPY DAEMON.JSON
    template: 
      src: "daemon.json" 
      dest: "{{ docker_config_path }}/daemon.json"
    notify: restart docker
