---
- hosts: k8s
  gather_facts: False
  roles:
    - role: nginx
      vars:
        master: 
        - '172.17.13.188'
        - '172.17.13.188'
        - '172.17.13.188'

    - role: docker
      vars:
        docker_config_path: '/etc/docker/'
        harbor: '"reg1.syswin.com"'

    - role: kubeadm
      vars:
        version: '1.19.3'
        kubelet_config_path: "/etc/sysconfig/"

- hosts: k8s_master_first
  roles:
    - role: master_f
      vars:
        join_cluster: 'echo `kubeadm token create --print-join-command` --control-plane'

- hosts: k8s_master_second
  roles:
    - role: master_s

- hosts: k8s_node
  roles:
    - role: node
